Repository ThatConference/that-api-gateway, pull requests merged in 2019-12, with the labels that each got.

#13 adds pino, moves schema creation to the instance rather than the request
  package-lock.json
  package.json
  src/expressLogOptions.js
  src/graphql/index.js
  src/index.js
Labels: enhancement

#15 Updates the helper install script with missing npm install for sessions
  npm-install-in-apis.sh
Labels: bug

#16 Add version info based on commit hash.
  .github/workflows/pushMasterCi.yml
  .vscode/settings.json
  src/index.js
Labels: enhancement

#20 fixed debug namespaces
  package.json
  src/graphql/index.js
  src/index.js
Labels: enhancement

#21 handle passthrough headers better
  src/graphql/index.js
  src/index.js
Labels: bug, enhancement
